# Generated by Django 2.2 on 2021-09-14 13:03

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=61, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=31, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=account.models.profile_picture_location)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_bloger', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
