# Generated by Django 2.2 on 2021-09-14 16:22

from django.db import migrations, models
import mess.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=mess.models.mess_picture_location),
        ),
        migrations.AlterField(
            model_name='mess',
            name='price_range',
            field=models.CharField(max_length=15),
        ),
    ]
