# Generated by Django 2.2 on 2021-09-15 13:33

from django.db import migrations, models
import django.db.models.deletion
import mess.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_auto_20210914_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='details',
            field=models.TextField(default=1, max_length=501),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=mess.models.mess_picture_location)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=mess.models.mess_picture_location)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=mess.models.mess_picture_location)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=mess.models.mess_picture_location)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to=mess.models.mess_picture_location)),
                ('name', models.CharField(max_length=31, unique=True)),
                ('price', models.IntegerField()),
                ('mess_type', models.CharField(max_length=15)),
                ('square_fit', models.IntegerField()),
                ('total_room', models.IntegerField(default=1)),
                ('washroom', models.IntegerField(default=1)),
                ('is_attach_washroom', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('corridor', models.BooleanField(default=False)),
                ('total_windows', models.IntegerField(default=1)),
                ('room_capability', models.IntegerField(default=1)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.Mess')),
            ],
        ),
    ]
