# Generated by Django 2.2 on 2021-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_auto_20210915_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='details',
            field=models.TextField(default=1, max_length=501),
            preserve_default=False,
        ),
    ]
